# Generated by Django 2.0.7 on 2019-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogarticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='博客标题')),
                ('content', models.TextField(verbose_name='博文')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_secret', models.IntegerField(choices=[(0, '可见'), (1, '私密')], default=1, verbose_name='对游客会否可见')),
                ('times', models.BigIntegerField(default=0, verbose_name='博文浏览量')),
                ('listimage', models.TextField(blank=True, null=True, verbose_name='列表图片')),
                ('detailimage', models.TextField(blank=True, null=True, verbose_name='详细图片图片')),
            ],
            options={
                'db_table': 'blog_blogarticle',
            },
        ),
        migrations.CreateModel(
            name='blogtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, verbose_name='标签')),
                ('blog', models.ManyToManyField(to='blog.blogarticle', verbose_name='博客')),
            ],
            options={
                'db_table': 'blog_blogtag',
            },
        ),
    ]
